package ch.unil.pafanalysis.controllers

import ch.unil.pafanalysis.results.model.InitialResult
import ch.unil.pafanalysis.results.service.ResultRepository
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.web.bind.annotation.*

@RestController
// This means that this class is a Controller
@RequestMapping(path = ["/result"]) // This means URL's start with /demo (after Application path)
class ResultController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private var resultRepository: ResultRepository? = null

    @PostMapping("/add")
    fun addResult(@RequestParam name: String){
        val res = InitialResult(0, name)
        resultRepository?.save(res)
    }


    @GetMapping("/list")
    fun listResults(): Iterable<InitialResult>? {
        return resultRepository?.findAll()
    }
}